Code cov
mcode/clinical-trial-matching-engine pull request #43
Opened 2020-11-27 21:27 UTC by 19ngaddam

Pull requests into the clinical-trial-matching-engine require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] Make sure test coverage didn’t decrease. If you are allowing the test coverage to drop, leave an explanation as to why:
- [ ]	Does an update need to be made to the documentation with these changes?
- [ ]	Does an update need to be made to the service wrappers/template?
- [ ]	Does an update need to be made to the service library?
- [ ] Was the new feature tested by unit tests?
- [ ] Was the new feature tested by a manual, end-to-end test?

2021-02-03 18:03 UTC, zlister approved these changes

2021-02-03 18:11 UTC, dmpotter44 requested changes
I'm unclear on why there's a random style rule in the index.html file and not inside either styles.css or one of the component stylesheets.

2021-02-03 18:11 UTC, dmpotter44 commented on src/index.html
> +  </style>
What is this and why isn't it in a CSS file?

2021-02-04 14:44 UTC, dmpotter44 commented on src/app/app.component.html
> +              style=" position: relative;display: inline-block;"> <span class="color1 filterText pointer" :hover>
What is `:hover`? `:hover` is a CSS "pseudoclass" - it represents the element when it's being hovered, it doesn't need to be in the HTML. I think syntactically `:hover` is valid as a namespace-less attribute called `hover` but it doesn't need to be in the HTML.

2021-02-04 15:21 UTC, dmpotter44 approved these changes

2021-02-04 15:37 UTC, zlister approved these changes

2021-02-04 15:37 UTC, merged